return {
    ActiveLSP = "",
    ActiveTS = " ",
    BufferClose = "",
    DapBreakpoint = "",
    DapBreakpointCondition = "",
    DapBreakpointRejected = "",
    DapLogPoint = "",
    DapStopped = "",
    DefaultFile = "",
    Diagnostic = "",
    DiagnosticError = "",
    DiagnosticHint = "",
    DiagnosticInfo = "",
    DiagnosticWarn = "",
    Ellipsis = "",
    FileModified = "",
    FileReadOnly = "",
    FoldClosed = "",
    FoldOpened = "",
    Git = "",
    GitAdd = "",
    GitBranch = "",
    GitChange = "M",
    GitConflict = "",
    GitDelete = "D",
    GitIgnored = "",
    GitRenamed = "M",
    GitStaged = "",
    GitUnstaged = "U",
    GitUntracked = "U",
    LSPLoaded = "",
    LSPLoading1 = "",
    LSPLoading2 = "",
    LSPLoading3 = "",
    MacroRecording = "",
    Paste = "",
    Search = "",
    Selected = "",
    TabClose = ""
    -- text_icons = {
    --     ActiveLSP = "LSP:",
    --     ActiveTS = "",
    --     BufferClose = "x",
    --     DefaultFile = "[F]",
    --     Diagnostic = "",
    --     DiagnosticError = "X",
    --     DiagnosticHint = "?",
    --     DiagnosticInfo = "i",
    --     DiagnosticWarn = "!",
    --     Ellipsis = "...",
    --     FileModified = "*",
    --     FileReadOnly = "[lock]",
    --     FolderClosed = "[D]",
    --     FolderEmpty = "[E]",
    --     FolderOpen = "[O]",
    --     Git = "",
    --     GitAdd = "[+]",
    --     GitBranch = "",
    --     GitChange = "[/]",
    --     GitConflict = "[!]",
    --     GitDelete = "[-]",
    --     GitIgnored = "[I]",
    --     GitRenamed = "[R]",
    --     GitStaged = "[S]",
    --     GitUnstaged = "[U]",
    --     GitUntracked = "[?]",
    --     LSPLoaded = "",
    --     LSPLoading1 = "",
    --     LSPLoading2 = "",
    --     LSPLoading3 = "",
    --     MacroRecording = "Recording:",
    --     NeovimClose = "X"
    -- },
    -- plugins = {
    --     {
    --         "onsails/lspkind.nvim",
    --         opts = function(_, opts)
    --             -- use codicons preset
    --             opts.preset = "codicons"
    --             -- set some missing symbol types
    --             opts.symbol_map = {
    --                 Array = "",
    --                 Boolean = "",
    --                 Key = "",
    --                 Namespace = "",
    --                 Null = "",
    --                 Number = "",
    --                 Object = "",
    --                 Package = "",
    --                 String = ""
    --             }
    --             return opts
    --         end
    --     }
    -- }
}
